# Generated by Django 3.1.3 on 2023-04-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230417_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='course_id',
        ),
    ]
